- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable postgres at boot
  service:
    name: postgresql
    enabled: yes

- name: stat data folder
  stat:
    path: /var/lib/pgsql/data
  register: dataDir

- name: initilize postgres
  command: postgresql-setup initdb
  when: dataDir.stat.islnk is not defined

- name: initilize postgres some more
  command: chkconfig postgresql on
  when: dataDir.stat.islnk is not defined

- name: start postgres
  service:
    name: postgresql.service
    state: started